/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
/**
 * PD12: Led
 *
 * PA5->LED
 * PC13 -> Boton de usuario
 */
/*Includes -------------------------------------------------------------------*/
#include "stm32f4xx.h"
#include "hvac_ll_driver.h"
#include "delay.h"
#include "button.h"
#include <stdio.h>
#include "lcd.h"
/*Defines --------------------------------------------------------------------*/


/*Typedefs -------------------------------------------------------------------*/

/*Global variables -----------------------------------------------------------*/
Button_t sw1;
Button_t sw2;
LCD_t display;
usart_rx_data_t rxData;
uint8_t *pointer;
uint8_t rx_buffer[256];
/*Function prototype ---------------------------------------------------------*/
/**
 * 1: cuando el boton este presionado
 */
uint8_t readButton(uint8_t pin);


int main(void)
{
	/*Local variables --------------------------------------------------------*/
	/*
	 * base tiempo
	 * ticks = Fsysclk/freq
	 * ticks = 16E+6/1000
	 * ticks = 16000
	 */
	SystemCoreClockUpdate();
	SysTick_Config(SystemCoreClock / 1000);
	NVIC_SetPriority(SysTick_IRQn, 15);
	/**
	 * hardware init
	 */
	hvac_io_init();
	/**
	 * button
	 */
	button_init(&sw1, readButton, getTicks, 20, 0);
	button_init(&sw2, readButton, getTicks, 15, 1);
	/**
	 * LCD
	 */
	lcd_init(&display, hvac_lcd_write_nb, delay_ms, 20, 4);

	lcd_printf(&display, 0, 0, "DISPLAY\r\nSTM32-2024\r\n");

	/**
	 * UART
	 */
	hvac_uart_init(USART2);
	/**
	 * recepcion de datos
	 */
	pointer = (uint8_t *)rx_buffer;

	printf("HVAC APP Init...\r\n");
	printf("Comp. V: %s %s\r\n", __DATE__, __TIME__);
	/* Loop forever */
	for(;;){
		if(button_on_press(&sw1)){
			lcd_clear(&display);
			lcd_puts(&display, 0, 0,"button on press");
		}
		else if(button_press_time_is_greater(&sw1, 3000, 1)){
			lcd_clear(&display);
			lcd_puts(&display, 0, 0, "button press to 3 sec.");
		}else if(button_on_release(&sw1)){
			lcd_clear(&display);
			lcd_puts(&display, 0, 0,"button on release");
		}
		/**
		 * process data
		 */
		if(hvac_flags & HVAC_RX_UART_DATA){
			hvac_flags &=~ HVAC_RX_UART_DATA;
			if(rxData.header == 0xAA){
				printf("rx data: cmd [0x%X]\r\n", rxData.cmd);
				//Procesar el comando
				switch(rxData.cmd){
				case 1:	//led on/off
					if(rxData.payload[0] == 1){
						printf("LED on\r\n");
						GPIOX_ODR(STATUS) = 1;
					}else{
						printf("LED off\r\n");
						GPIOX_ODR(STATUS) = 0;
					}
					break;
				case 2: //get status
					//send hvac status
					printf("hvac normal state\r\n");
					break;
				default:
					printf("error command! not found\r\n");
				}
			}
		}
	}
}

/*Function definition --------------------------------------------------------*/
uint8_t readButton(uint8_t pin){
	uint8_t state = 0;
	switch(pin){
	case 0:
		state = GPIOX_IDR(SW1);				//pull down
		break;
	case 1:
		state = GPIOX_IDR(SW2) == 0 ? 1 : 0;//pulsador en pull up
		break;
	}
	return state;
}
int __io_putchar(int ch){
	while(!(USART2->SR & USART_SR_TXE));

	USART2->DR = (uint8_t)ch;
	return ch;
}
