/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
/**
 * PD12: Led
 *
 * PA5->LED
 * PC13 -> Boton de usuario
 */
/*Includes -------------------------------------------------------------------*/
#include "stm32f4xx.h"
#include "hvac_ll_driver.h"
#include "delay.h"
#include "button.h"
#include <stdio.h>
#include "lcd.h"
#include "dht.h"
/*Defines --------------------------------------------------------------------*/
#define DHT_PIN	 E, 4

/*Typedefs -------------------------------------------------------------------*/

/*Global variables -----------------------------------------------------------*/
Button_t sw1;
Button_t sw2;
LCD_t display;
usart_rx_data_t rxData;
uint8_t *pointer;
uint8_t rx_buffer[256];

DHT_t am2301;
/*Function prototype ---------------------------------------------------------*/
/**
 * 1: cuando el boton este presionado
 */
uint8_t readButton(uint8_t pin);


int main(void)
{
	/*Local variables --------------------------------------------------------*/
	/*
	 * base tiempo
	 * ticks = Fsysclk/freq
	 * ticks = 16E+6/1000
	 * ticks = 16000
	 */
	SystemCoreClockUpdate();
	SysTick_Config(SystemCoreClock / 1000);
	NVIC_SetPriority(SysTick_IRQn, 15);
	/**
	 * hardware init
	 */
	hvac_io_init();
	/**
	 * button
	 */
	button_init(&sw1, readButton, getTicks, 20, 0);
	button_init(&sw2, readButton, getTicks, 15, 1);
	/**
	 * LCD
	 */
	lcd_init(&display, hvac_lcd_write_nb, delay_ms, 20, 4);

	lcd_printf(&display, 0, 0, "DISPLAY\r\nSTM32-2024\r\n");

	/**
	 * UART
	 */
	hvac_uart_init(USART2);
	/**
	 * recepcion de datos
	 */
	pointer = (uint8_t *)rx_buffer;

	printf("HVAC APP Init...\r\n");
	printf("Comp. V: %s %s\r\n", __DATE__, __TIME__);

	/* Loop forever */
	/**
	 * pin IT con ambos flancos
	 */
	GPIOX_CLK_EN(DHT_PIN);
	GPIOX_MODER(DHT_PIN, 0x1);

	EXTI->IMR |= 1<<4; 	//PIN PE6
	EXTI->RTSR |= 1<<4;
	EXTI->FTSR |= 1<<4;

	EXTI->PR |= 1<<4;
	RCC->APB2ENR |= RCC_APB2ENR_SYSCFGEN;
	SYSCFG->EXTICR[1] &=~ SYSCFG_EXTICR2_EXTI4;
	SYSCFG->EXTICR[1] |= SYSCFG_EXTICR2_EXTI4_PE;

	NVIC_EnableIRQ(EXTI4_IRQn);

	/**
	 * timer}
	 *
	 * FREQ: 1MHZ (CONTEO)
	 *
	 * FREQ = 16E+6 / (PSC +1)
	 * PSC = 15
	 */
	RCC->APB1ENR |= RCC_APB1ENR_TIM2EN;

	TIM2->CR1 = 0;
	TIM2->PSC = 15;
	TIM2->ARR = 0xFFFFFFFF;
	TIM2->CR1 |= TIM_CR1_CEN;

	/**
	 * sensor am2301 init
	 */
	DHT_Init(&am2301, GPIOE, 4, TIM2, DHT_Type_AM2301);

	float temp;
	float hum;

	for(;;){
		DHT_readData(&am2301, &temp, &hum);
		delay_ms(1000);
	}
}

/*Function definition --------------------------------------------------------*/
uint8_t readButton(uint8_t pin){
	uint8_t state = 0;
	switch(pin){
	case 0:
		state = GPIOX_IDR(SW1);				//pull down
		break;
	case 1:
		state = GPIOX_IDR(SW2) == 0 ? 1 : 0;//pulsador en pull up
		break;
	}
	return state;
}
int __io_putchar(int ch){
	while(!(USART2->SR & USART_SR_TXE));

	USART2->DR = (uint8_t)ch;
	return ch;
}
