/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
/*Includes -------------------------------------------------------------------*/
#include "stm32f4xx.h"
/*Defines --------------------------------------------------------------------*/

/*Typedefs -------------------------------------------------------------------*/

/*Global variables -----------------------------------------------------------*/

/*Function prototype ---------------------------------------------------------*/



int main(void)
{
    /* Loop forever */
	for(;;);
}

/*Function definition --------------------------------------------------------*/
